# Generated by Django 6.1.1 on 2026-10-05 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cargar_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
    ]
